In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("amazon_sales_dataset.csv")
df.head(5)

,order_id,order_date,ship_date,delivery_date,order_status,customer_id,customer_name,country,state,city,...,product_name,category,sub_category,brand,quantity,unit_price,discount,shipping_cost,total_sales,payment_method
0,A10000,2026-01-31,2026-01-31,2026-01-08,Delivered,C5691,Ricky Potter,India,South Carolina,New Joe,...,without,Home,Furniture,Doyle-Jordan,3,42467.79,0.26,60.85,94339.3438,Card
1,A10001,2026-01-20,2026-02-03,2026-02-03,Delivered,C9811,Chris Davenport,India,Tennessee,Madisonmouth,...,school,Home,Furniture,Davis LLC,2,36138.76,0.24,112.96,55043.8752,COD
2,A10002,2026-01-15,2026-02-07,2026-01-03,Delivered,C7341,Timothy Gallagher,India,Iowa,East Larryberg,...,I,Electronics,Laptop,Watson and Sons,4,47148.93,0.14,64.11,162256.4292,UPI
3,A10003,2026-01-18,2026-01-15,2026-01-20,Delivered,C4012,Angela Collins,India,Kentucky,South Margaretshire,...,step,Electronics,Laptop,"Sandoval, Buckley and Solis",1,18487.99,0.06,114.15,17492.8606,Card
4,A10004,2026-01-27,2026-01-04,2026-01-23,Delivered,C1328,David Davidson DDS,India,North Dakota,Velasquezview,...,bit,Home,Kitchen,"Key, Bautista and Bowen",1,1742.25,0.10,40.47,1608.4950,UPI

In [3]:
df.shape

(10000, 21)

In [7]:
df.columns

Index(['order_id', 'order_date', 'ship_date', 'delivery_date', 'order_status',
       'customer_id', 'customer_name', 'country', 'state', 'city',
       'product_id', 'product_name', 'category', 'sub_category', 'brand',
       'quantity', 'unit_price', 'discount', 'shipping_cost', 'total_sales',
       'payment_method'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        10000 non-null  object
 1   order_date      10000 non-null  object
 2   ship_date       10000 non-null  object
 3   delivery_date   10000 non-null  object
 4   order_status    10000 non-null  object
 5   customer_id     10000 non-null  object
 6   customer_name   10000 non-null  object
 7   country         10000 non-null  object
 8   state           10000 non-null  object
 9   city            10000 non-null  object
 10  product_id      10000 non-null  object
 11  product_name    10000 non-null  object
 12  category        10000 non-null  object
 13  sub_category    10000 non-null  object
 14  brand           10000 non-null  object
 15  quantity        10000 non-null  int64
 16  unit_price      10000 non-null  float64
 17  discount        10000 non-null  float64
 18  shipping_cost   10000 non-null  float64
 19  total_sales     10000 non-null  float64
 20  payment_method  10000 non-null  object
dtypes: float64(4), int64(1), object(16)
memory usage: 1.6+ MB

In [9]:
df.describe()

          quantity    unit_price      discount  shipping_cost    total_sales
count  10000.00000  10000.000000  10000.000000   10000.000000   10000.000000
mean       3.01440  25126.511133      0.149968      85.053192   64212.910555
std        1.42035  14343.922332      0.086828      37.575284   50992.635082
min        1.00000    214.200000      0.000000      20.010000     309.939600
25%        2.00000  12657.827500      0.070000      52.507500   24037.196775
50%        3.00000  24880.490000      0.150000      84.995000   50287.177500
75%        4.00000  37544.640000      0.220000     117.680000   93417.891825
max        5.00000  49981.880000      0.300000     149.950000  249155.530000

In [10]:
df.isnull().sum()

order_id          0
order_date        0
ship_date         0
delivery_date     0
order_status      0
customer_id       0
customer_name     0
country           0
state             0
city              0
product_id        0
product_name      0
category          0
sub_category      0
brand             0
quantity          0
unit_price        0
discount          0
shipping_cost     0
total_sales       0
payment_method    0
dtype: int64

In [14]:
numeric_columns= df.select_dtypes(include=['int64','float64'])
numeric_columns.columns

Index(['quantity', 'unit_price', 'discount', 'shipping_cost', 'total_sales'], dtype='object')

In [15]:
categorical_columns= df.select_dtypes(include=['object'])
categorical_columns.columns

Index(['order_id', 'order_date', 'ship_date', 'delivery_date', 'order_status',
       'customer_id', 'customer_name', 'country', 'state', 'city',
       'product_id', 'product_name', 'category', 'sub_category', 'brand',
       'payment_method'],
      dtype='object')

In [20]:
df.duplicated().sum()

0

In [17]:
df.nunique()

order_id          10000
order_date           41
ship_date            41
delivery_date        41
order_status          1
customer_id        6016
customer_name      9412
country               1
state                50
city               7647
product_id          900
product_name        971
category              3
sub_category          7
brand              8659
quantity              5
unit_price         9992
discount             31
shipping_cost      6973
total_sales       10000
payment_method        4
dtype: int64

In [18]:
date_columns = ['order_date','ship_date','delivery_date']


for col in date_columns:
    df[col]=pd.to_datetime(df[col])

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        10000 non-null  object
 1   order_date      10000 non-null  datetime64[ns]
 2   ship_date       10000 non-null  datetime64[ns]
 3   delivery_date   10000 non-null  datetime64[ns]
 4   order_status    10000 non-null  object
 5   customer_id     10000 non-null  object
 6   customer_name   10000 non-null  object
 7   country         10000 non-null  object
 8   state           10000 non-null  object
 9   city            10000 non-null  object
 10  product_id      10000 non-null  object
 11  product_name    10000 non-null  object
 12  category        10000 non-null  object
 13  sub_category    10000 non-null  object
 14  brand           10000 non-null  object
 15  quantity        10000 non-null  int64
 16  unit_price      10000 non-null  float64
 17  discount        10000 non-null  float64
 18  shipping_cost   10000 non-null  float64
 19  total_sales     10000 non-null  float64
 20  payment_method  10000 non-null  object
dtypes: datetime64[ns](3), float64(4), int64(1), object(13)
memory usage: 1.6+ MB

# Data Quality Report
## Dataset Name : Amazon Sales Dataset


Number Of Rows:10000
Number Of Columns:21

Numeric Columns:['quantity', 'unit_price', 'discount', 'shipping_cost', 'total_sales']

Categorical Columns:['order_id', 'order_date', 'ship_date', 'delivery_date', 'order_status',
       'customer_id', 'customer_name', 'country', 'state', 'city',
       'product_id', 'product_name', 'category', 'sub_category', 'brand',
       'payment_method']

Date Column:['order_date','ship_date','delivery_date']

Missing Values:0

Duplicate Row:0

Primary Key:[order_id]


Remarks:The dataset was successfully loaded and its is suitable for analysis. There are no missing values or duplicate records were found.Dataset is ready for EDA